version: '3.8'
services:
  DB:
    image: mySQL
    volumes:
      data:/app
    ports:
      -3306:3306
  WebServer:
    image: 'nginx:stable-alpine'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  Php:
    build: 
      context: ./php
      dockerfile: php.dockerfile
    volumes:
       # Delegated in this context allows to write to your bind mount 
       #gradually with overloading your volume for performance issue
      -./src:/var/www/html:delegated 
  compose:
  composer:
  npm:
  artisian:
