version: 2
sources:

  - name: northwind
    schema: dl_northwind
    tables:
      - name: customer
        identifier: customer
      - name: staff_acl
        identifier: employee_privileges
      - name: staff
        identifiers: employees
      - name: stocks_transaction
        identifiers: inventory_transaction_types
      - name: inventory_transactions
      - name: invoices
      - name: order_details
      - name: orders
      - name: order_details_status
      - name: orders_tax_status
      - name: privileges
      - name: products
      - name: purchase_order_details
      - name: purchase_order_status
      - name: purchase_orders
      - name: sales_reports
      - name: shippers
      - name: strings
      - name: suppliers
      