version: "3.1"

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: postgres
      POSTGRES_DB: "postgres"
    volumes:
      - /home/samson/my_sandbox/myPythonprojects/Docker/Postgres/postgres-db-volume:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 5432:5432
  # pgadmin:
  #   image: dpage/pgadmin4:4.18
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@linux.com
  #     PGADMIN_DEFAULT_PASSWORD: ''
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8081:80"
  #   user: root
    # volumes:
    #   - /home/samson/my_sandbox/myPythonprojects/Docker/Postgres/pgadmin-data:/var/lib/pgadmin
    # links:
    #   - "db:pgsql-server"
volumes:
  postgres-db-volume:
  pgadmin-data:
