snowflakeDWH:
  outputs:
    dev:
      account: qbolsxy-pt61262
      database: AIRBNB
      password: 
      role: SYSADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: test
      warehouse: COMPUTE_WH
  target: dev
