# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_DEFAULT_EMAIL: email@gmail.com
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - 8085:80
