"""Initial migration.

Revision ID: 236d78f19332
Revises: 8476a7c3ef92
Create Date: 2023-10-06 21:08:36.792002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236d78f19332'
down_revision = '8476a7c3ef92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='CareerPath'
    )
    op.create_table('career_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=300), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['CareerPath.courses.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['CareerPath.Program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('course_status',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=300), nullable=False),
    sa.Column('Unit', sa.Integer(), nullable=False),
    sa.Column('semesta_id', sa.Integer(), nullable=True),
    sa.Column('course_status_id', sa.String(length=300), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('career_path_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['career_path_id'], ['CareerPath.career_path.id'], ),
    sa.ForeignKeyConstraint(['course_status_id'], ['CareerPath.course_status.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['CareerPath.Program.id'], ),
    sa.ForeignKeyConstraint(['semesta_id'], ['CareerPath.semester.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('prerequisite_waiver',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name_of_requester', sa.String(length=100), nullable=False),
    sa.Column('Prequisiste_status', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=300), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('waiver_request', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('programID', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('student_advisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('Program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('program_categories', sa.String(length=150), nullable=False),
    sa.Column('Desc', sa.String(length=300), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['CareerPath.student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('preRequisite',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=300), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['CareerPath.courses.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['CareerPath.course_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    op.create_table('Electives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('Desc', sa.String(length=300), nullable=False),
    sa.Column('Unit', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['CareerPath.Program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='CareerPath'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Electives', schema='CareerPath')
    op.drop_table('preRequisite', schema='CareerPath')
    op.drop_table('Program', schema='CareerPath')
    op.drop_table('student_advisor', schema='CareerPath')
    op.drop_table('student', schema='CareerPath')
    op.drop_table('semester', schema='CareerPath')
    op.drop_table('prerequisite_waiver', schema='CareerPath')
    op.drop_table('courses', schema='CareerPath')
    op.drop_table('course_status', schema='CareerPath')
    op.drop_table('career_path', schema='CareerPath')
    op.drop_table('User', schema='CareerPath')
    # ### end Alembic commands ###
