apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-tls
  # The tls secret must be in the same namespace as the ingress object, before can use it.
  namespace: default
data:
  tls.crt:
  tls.key:
type: kubernetes.io/tls
