ALTER TABLE --TABLE NAME--
{
    RENAME TO CLAUSE|
    ADD COLUMN |
    DROP COLUMN |
    RENAME COLUMN CLAUSE
    ADD CONSTRAINT CLAUSE|
    ADD PARTITION CLAUSE|
    RENAME PARTITION CLAUSE|
    RECOVER PARTITION CLAUSE|
    SET TBLPROPERTIES |
    UNSET TBLPROPERTIES |
    SET SERDE CLAUSE |
    SET OWNER to CLAUSE |
    SET LOCATION TO CLAUSE |
}