/*
NOTE 
- WHEN YOU SPECIFY AN EXTERNAL LOCATION FOR A CATALOG DURING CREATION IT TAKES PREDENCE OVER THE METASTORE UNITY STORE
- WHEN YOU SPECIFY AN EXTERNAL LOCATION FOR A SCHEMA DURING CREATION IT TAKES PREDENCE OVER THE UNITY STORE FOR THE CATALOG
- WHEN YOU SPECIFY AN EXTERNAL LOCATION FOR A TABLE DURING CREATION IT TAKES PREDENCE OVER THE UNITY STORE FOR THE SCHEMA
*/

--CREATE MANAGED Table or Schema WITH AN  external LOCATION
CREATE SCHEMA course_project.temp_schema 
MANAGED LOCATION 'abfss://extschemaloc@dbsstg001extloc.dfs.core.windows.net/'

CREATE  TABLE course_project.temp_schema.citybike_TEMP (COL1 STRING )

DESCRIBE formatted course_project.temp_schema.citybike_TEMP 


--CREATE MANAGED Table or Schema WITH AN  external LOCATION
CREATE CATALOG course_project
MANAGED LOCATION 'abfss://extschemaloc@dbsstg001extloc.dfs.core.windows.net/'

-- DROP SCHEMA AND CASCADE TO ASSOCIATED TABLES THIS IS A SOFT DELETE for 30DAYS
DROP SCHEMA course_project.temp_schema CASCADE;

-- RESTORE DROP TABLED
RESTORE TABLE schema_name.table_name TO VERSION AS OF <version_number>;

-- DESCRIBE HISTORY
DESCRIBE HISTORY SCHEMA_NAME TABLE_NAME 