--Creat a Virtual Data Warehouse 
USE ROLE SYSADMIN;

CREATE WAREHOUSE ETL_WH
WAREHOUSE_SIZE = XSMALL
MAX_CLUSTER_COUNT = 3
MAX_CLUSTER_COUNT = 1
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 300 --SUSPEND AFTER 5 MINUTES  (300 SECONDS) OF INACTIVIVTY
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
