apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv-logs
  namespace: airflow
spec:
  capacity:
    storage: 5Gi
  accessModes:
  #ReadWriteOnce - The volume can be mounted as read-write by a single node
  #readWriteMany - The volume can be mounted as read-write by many nodes
  #readOnlyMany - The volume can be mounted read-only by many nodes
    - ReadWriteMany
  storageClassName: path-storage
  hostPath:
    path: /Users/s.eromonsei/storage/logs

---
# write a persistence volume claim for the kubernetes volume
# Claim  must exist in the same namespace as the as the POD using the Claim.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pv-logs
  namespace: airflow
spec:
  storageClassName: path-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
