name: GitHub Actions Demo
on: 
  push:
    branches:
      - main # or the name of your main branch
jobs:
     Demo-test:
      runs-on: ubuntu-latest
      steps:
        - run: echo " A job has been pushed to your repository ${{github.repository}} "
