# GitHub Actions Workflow for ETL Pipeline

name: ETL Pipeline

# ---------------------
# Event Workflows Section
# ---------------------
on:
  push: 
    branches: [main]            # Workflow is triggered on push to the 'main' branch
  pull_request:
    branches: [main]            # Workflow is triggered on pull request to the 'main' branch
  schedule:
    - cron: '0 0 * * *'         # Workflow is scheduled to run every day at 12:00 AM

# ---------------------
# Environment Variables Section
# ---------------------
env:
  DBT_PROFILES_DIR: ./Engineering/DBT/BigQuey/bigQueyEDW   # Environment variable for dbt profiles directory
  DBT_PROJECT_DIR: ./Engineering/DBT/BigQuey/bigQueyEDW    # Environment variable for dbt project directory


# ---------------------
# Jobs Section
# ---------------------
jobs:
  etl:
    runs-on: ubuntu-latest        # The job runs on the latest Ubuntu environment
    
    # ---------------------
    # Actions (Steps) Section
    # ---------------------
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Action to check out the repository's code
      
      - name: Set up Python
        uses: actions/setup-python@v2   # Action to set up Python environment
        with:
          python-version: '3.11'        # Set Python version to 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi   # Install dependencies using pip if requirements.txt exists

      - name: Test dbt Prod Model
        run: |
          cd $DBT_PROFILES_DIR
          dbt test --target dev          # Run dbt test on the development environment

      - name: Run dbt Prod
        run: |
          dbt debug                      # Run dbt debug to check configuration
          dbt compile                    # Compile dbt models
          dbt run --target prod -m warehouse   # Run dbt models in production for the 'warehouse' model
